#!/usr/bin/env node
// What is this model, and what stands between it and being a component?
//
// WHY THIS EXISTS. Everything the engine has met so far was generated by
// make-test-glb.mjs, which means it has only ever seen files that were already
// correct. A real supplier model is a different animal: it arrives in whatever
// units the CAD package felt like, with a scale factor baked into a node, with
// 400k triangles, with node names full of characters that three.js silently
// mangles, and with no idea what a snap plane is. Loading one and reading the
// error is a poor way to find that out, because the loader stops at the FIRST
// problem and a real file has several.
//
// So this reports ALL of them at once, in the order they have to be fixed, using
// the same error codes extractComponent throws. It never modifies anything.
//
// NO DEPENDENCIES, AND NOT THROUGH THREE.JS, both on purpose:
//   * three.js's GLTFLoader strips dots and colons from node names. That cost us
//     a debugging cycle once already (md-snap.carcass-side.left arrived as
//     md-snapcarcass-sideleft and zero snaps were found). An inspector that
//     reported the mangled names would hide the very problem it exists to find.
//   * Bounding boxes come from accessor min/max, which the glTF spec requires on
//     POSITION. No vertex data is decoded, so a 200MB file inspects as fast as a
//     6KB one, and Draco-compressed files still report their extents.
//
// Usage:
//   node tools/inspect-model.mjs <file.glb|file.gltf> [more files...]
//   node tools/inspect-model.mjs --json <file.glb>     machine-readable
//   node tools/inspect-model.mjs <dir>                 every model in a folder

import { readFileSync, statSync, readdirSync } from 'node:fs';
import { join, extname, basename, dirname } from 'node:path';

// ---------------------------------------------------------------- constants
// These mirror src/engine/component.js. If that file's rules change, these
// must follow, and the audit below says so in its own output.
const BODY_NODE = 'body';
const SNAP_PREFIX = 'md-snap.';
const GRID_PREFIX = 'md-grid.';
const COLLISION_PREFIX = 'col-';
const DIMENSION_NODE = 'dim';
const SCALE_TOLERANCE_MM = 1;
// Stands in for a ratio against a zero declared dimension, which is a fault in
// its own right and must not become NaN and vanish from the report.
const NULL_RATIO = Infinity;

// three.js Object3D.name sanitisation. Kept in sync with src/three/loadGlb.js.
// NOT global: a /g regex makes .test() stateful, so it reports every OTHER
// match and the count comes out wrong. Found while writing this file, which is
// a fair warning about how quietly that mistake passes.
const THREE_RESERVED = /[[\].:/]/;
const sanitiseThreeName = (name) => String(name).replace(/\s/g, '_').replace(/[[\].:/]/g, '');

// A component in this domain runs from a bracket to a wardrobe. Used ONLY to
// guess units when nothing declares them, and deliberately loose: several
// readings of the same file can look plausible, and the tool should say so
// rather than pick one and sound certain.
const PLAUSIBLE_MM = { smallestAtLeast: 1, largestFrom: 20, largestTo: 4000 };
// The band most furniture parts fall in, used to RANK plausible readings.
const TYPICAL_MM = { from: 200, to: 2200 };

const READABLE = new Set(['.glb', '.gltf']);
const KNOWN_UNREADABLE = {
  '.stp': 'STEP (CAD)', '.step': 'STEP (CAD)', '.igs': 'IGES (CAD)', '.iges': 'IGES (CAD)',
  '.sldprt': 'SolidWorks part', '.sldasm': 'SolidWorks assembly', '.ipt': 'Inventor part',
  '.fbx': 'FBX', '.obj': 'OBJ', '.dae': 'COLLADA', '.3ds': '3D Studio', '.max': '3ds Max scene',
  '.blend': 'Blender scene', '.skp': 'SketchUp', '.dwg': 'AutoCAD', '.c4d': 'Cinema 4D',
  '.usd': 'USD', '.usdz': 'USDZ', '.ply': 'PLY', '.stl': 'STL',
};

// ---------------------------------------------------------------- container

/** Pull the glTF JSON (and the binary chunk, if any) out of a file. */
function readGltf(path) {
  const ext = extname(path).toLowerCase();
  const bytes = readFileSync(path);

  if (ext === '.gltf') {
    const json = JSON.parse(bytes.toString('utf8'));
    return { json, binary: null, container: 'glTF (JSON)', bytes: bytes.length };
  }

  // GLB: 12-byte header then length-prefixed chunks.
  if (bytes.length < 12) throw new Error('File is too short to be a GLB.');
  const magic = bytes.readUInt32LE(0);
  if (magic !== 0x46546c67) {
    throw new Error(
      `Not a GLB: expected magic "glTF", got 0x${magic.toString(16)}. `
      + 'If this is a .glb that another tool wrote, it may be a renamed .gltf.',
    );
  }
  const version = bytes.readUInt32LE(4);
  if (version !== 2) throw new Error(`GLB version ${version}; only version 2 is supported.`);

  let offset = 12;
  let json = null;
  let binary = null;
  while (offset + 8 <= bytes.length) {
    const chunkLength = bytes.readUInt32LE(offset);
    const chunkType = bytes.readUInt32LE(offset + 4);
    const start = offset + 8;
    const end = start + chunkLength;
    if (end > bytes.length) throw new Error('A GLB chunk runs past the end of the file.');

    if (chunkType === 0x4e4f534a) json = JSON.parse(bytes.subarray(start, end).toString('utf8'));
    else if (chunkType === 0x004e4942) binary = bytes.subarray(start, end);

    offset = end + ((4 - (chunkLength % 4)) % 4);
  }

  if (!json) throw new Error('GLB contains no JSON chunk.');
  return { json, binary, container: 'GLB (binary)', bytes: bytes.length };
}

// ---------------------------------------------------------------- transforms

const IDENTITY = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];

/** Column-major 4x4 multiply, matching glTF's `matrix` layout. */
function multiply(a, b) {
  const out = new Array(16).fill(0);
  for (let c = 0; c < 4; c++) {
    for (let r = 0; r < 4; r++) {
      let sum = 0;
      for (let k = 0; k < 4; k++) sum += a[k * 4 + r] * b[c * 4 + k];
      out[c * 4 + r] = sum;
    }
  }
  return out;
}

/** A node's local matrix, from either `matrix` or TRS. */
function localMatrix(node) {
  if (node.matrix) return node.matrix.slice();

  const [tx, ty, tz] = node.translation || [0, 0, 0];
  const [x, y, z, w] = node.rotation || [0, 0, 0, 1];
  const [sx, sy, sz] = node.scale || [1, 1, 1];

  const x2 = x + x, y2 = y + y, z2 = z + z;
  const xx = x * x2, xy = x * y2, xz = x * z2;
  const yy = y * y2, yz = y * z2, zz = z * z2;
  const wx = w * x2, wy = w * y2, wz = w * z2;

  return [
    (1 - (yy + zz)) * sx, (xy + wz) * sx, (xz - wy) * sx, 0,
    (xy - wz) * sy, (1 - (xx + zz)) * sy, (yz + wx) * sy, 0,
    (xz + wy) * sz, (yz - wx) * sz, (1 - (xx + yy)) * sz, 0,
    tx, ty, tz, 1,
  ];
}

function applyMatrix(m, [x, y, z]) {
  const w = m[3] * x + m[7] * y + m[11] * z + m[15] || 1;
  return [
    (m[0] * x + m[4] * y + m[8] * z + m[12]) / w,
    (m[1] * x + m[5] * y + m[9] * z + m[13]) / w,
    (m[2] * x + m[6] * y + m[10] * z + m[14]) / w,
  ];
}

/** Transform an axis-aligned box by a matrix: all eight corners, re-bound. */
function transformBox(m, min, max) {
  const lo = [Infinity, Infinity, Infinity];
  const hi = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < 8; i++) {
    const corner = applyMatrix(m, [
      i & 1 ? max[0] : min[0],
      i & 2 ? max[1] : min[1],
      i & 4 ? max[2] : min[2],
    ]);
    for (let a = 0; a < 3; a++) {
      lo[a] = Math.min(lo[a], corner[a]);
      hi[a] = Math.max(hi[a], corner[a]);
    }
  }
  return { min: lo, max: hi };
}

/** Scale factors baked into a matrix — the classic source of a wrong size. */
function scaleOf(m) {
  const len = (a, b, c) => Math.hypot(m[a], m[b], m[c]);
  return [len(0, 1, 2), len(4, 5, 6), len(8, 9, 10)];
}

// ---------------------------------------------------------------- geometry

const TRIANGLES_FOR_MODE = {
  4: (count) => count / 3,           // TRIANGLES
  5: (count) => Math.max(0, count - 2), // TRIANGLE_STRIP
  6: (count) => Math.max(0, count - 2), // TRIANGLE_FAN
};

/** Triangles and local bounds for one mesh, from accessor metadata only. */
function meshSummary(json, meshIndex) {
  const mesh = json.meshes?.[meshIndex];
  if (!mesh) return null;

  let triangles = 0;
  let vertices = 0;
  let missingBounds = false;
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  const modes = new Set();
  const materials = new Set();

  for (const prim of mesh.primitives || []) {
    const mode = prim.mode ?? 4;
    modes.add(mode);
    if (prim.material != null) materials.add(prim.material);

    const position = json.accessors?.[prim.attributes?.POSITION];
    if (position) {
      vertices += position.count || 0;
      if (position.min && position.max) {
        for (let a = 0; a < 3; a++) {
          min[a] = Math.min(min[a], position.min[a]);
          max[a] = Math.max(max[a], position.max[a]);
        }
      } else {
        // Without min/max we would have to decode vertex data. The spec
        // requires them on POSITION, so their absence is itself worth saying.
        missingBounds = true;
      }
    }

    const count = prim.indices != null
      ? (json.accessors?.[prim.indices]?.count || 0)
      : (position?.count || 0);
    triangles += Math.round((TRIANGLES_FOR_MODE[mode] || (() => 0))(count));
  }

  const hasBounds = Number.isFinite(min[0]);
  return {
    name: mesh.name || null,
    triangles,
    vertices,
    modes: [...modes],
    materials: [...materials],
    missingBounds,
    min: hasBounds ? min : null,
    max: hasBounds ? max : null,
    primitives: (mesh.primitives || []).length,
  };
}

// ---------------------------------------------------------------- walk

/** Flatten the scene graph, resolving world transforms and world bounds. */
function flatten(json) {
  const sceneIndex = json.scene ?? 0;
  const scene = json.scenes?.[sceneIndex];
  const roots = scene?.nodes ?? json.nodes?.map((_, i) => i) ?? [];

  const flat = [];
  const seen = new Set();

  const visit = (index, parentMatrix, path) => {
    // A cycle in `children` is malformed but survives a naive walk forever.
    if (seen.has(index)) return;
    seen.add(index);

    const node = json.nodes?.[index];
    if (!node) return;

    const world = multiply(parentMatrix, localMatrix(node));
    const mesh = node.mesh != null ? meshSummary(json, node.mesh) : null;
    const worldBox = mesh?.min ? transformBox(world, mesh.min, mesh.max) : null;

    flat.push({
      index,
      name: node.name ?? `(unnamed node ${index})`,
      path: [...path, node.name ?? `#${index}`].join(' / '),
      hasMesh: node.mesh != null,
      mesh,
      world,
      worldScale: scaleOf(world),
      localScale: node.scale || null,
      min: worldBox?.min || null,
      max: worldBox?.max || null,
      children: (node.children || []).length,
      skin: node.skin != null,
      camera: node.camera != null,
    });

    for (const child of node.children || []) {
      visit(child, world, [...path, node.name ?? `#${index}`]);
    }
  };

  for (const root of roots) visit(root, IDENTITY, []);
  return { flat, sceneIndex, sceneName: scene?.name || null, extras: scene?.extras || null };
}

// ---------------------------------------------------------------- inspection

const mm = (metres) => Math.round(metres * 1000 * 100) / 100;

function unitCandidates(sizeInFileUnits) {
  // What the model would measure if the file's unit were each of these.
  const scales = { metres: 1000, centimetres: 10, millimetres: 1, inches: 25.4, feet: 304.8 };
  const rows = Object.entries(scales).map(([unit, toMm]) => {
    const dims = sizeInFileUnits.map((v) => Math.round(v * toMm * 10) / 10);
    const largest = Math.max(...dims);
    const smallest = Math.min(...dims.filter((d) => d > 0));
    const plausible = largest >= PLAUSIBLE_MM.largestFrom
      && largest <= PLAUSIBLE_MM.largestTo
      && (smallest === undefined || smallest >= PLAUSIBLE_MM.smallestAtLeast);
    // Distance from the typical furniture band, so the likeliest reading can be
    // named without hiding the others.
    const distance = largest < TYPICAL_MM.from ? TYPICAL_MM.from - largest
      : largest > TYPICAL_MM.to ? largest - TYPICAL_MM.to : 0;
    return { unit, dimsMm: dims, plausible, distance };
  });

  const best = rows.filter((r) => r.plausible).sort((a, b) => a.distance - b.distance)[0];
  return rows.map((r) => ({ ...r, likeliest: best ? r.unit === best.unit : false }));
}

export function inspect(path) {
  const ext = extname(path).toLowerCase();
  const size = statSync(path).size;

  if (!READABLE.has(ext)) {
    return {
      file: basename(path),
      readable: false,
      format: KNOWN_UNREADABLE[ext] || `unknown (${ext || 'no extension'})`,
      bytes: size,
      advice: KNOWN_UNREADABLE[ext]
        ? `${KNOWN_UNREADABLE[ext]} is not a runtime format. Convert to glTF/GLB first — `
          + 'Blender imports most of these and exports glTF 2.0. Convert BEFORE adding snap '
          + 'planes, because a conversion usually resets units and node names.'
        : 'Unrecognised extension. The pipeline reads .glb and .gltf.',
    };
  }

  const { json, binary, container } = readGltf(path);
  const { flat, sceneName, extras } = flatten(json);

  // ---- scene extent, in the file's own units ----------------------------
  const lo = [Infinity, Infinity, Infinity];
  const hi = [-Infinity, -Infinity, -Infinity];
  for (const n of flat) {
    if (!n.min) continue;
    for (let a = 0; a < 3; a++) {
      lo[a] = Math.min(lo[a], n.min[a]);
      hi[a] = Math.max(hi[a], n.max[a]);
    }
  }
  const hasExtent = Number.isFinite(lo[0]);
  const extent = hasExtent ? [hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]] : null;

  // ---- geometry totals --------------------------------------------------
  const meshNodes = flat.filter((n) => n.hasMesh);
  const triangles = meshNodes.reduce((s, n) => s + (n.mesh?.triangles || 0), 0);
  const vertices = meshNodes.reduce((s, n) => s + (n.mesh?.vertices || 0), 0);

  // ---- textures ---------------------------------------------------------
  const textures = (json.images || []).map((img, i) => ({
    index: i,
    name: img.name || null,
    uri: img.uri && !img.uri.startsWith('data:') ? img.uri : null,
    embedded: img.bufferView != null || (img.uri || '').startsWith('data:'),
    mimeType: img.mimeType || null,
    bytes: img.bufferView != null ? (json.bufferViews?.[img.bufferView]?.byteLength ?? null) : null,
  }));

  // ---- naming hazards ---------------------------------------------------
  // Sanitisation is only a PROBLEM when two different names collapse to the
  // same string — that is what buildNameMap refuses, because picking one at
  // random would attach a snap to the wrong face. Dots in a snap name are not a
  // problem at all: the loader reads names from the raw glTF JSON precisely so
  // that md-snap.<mask>.<label> survives.
  const sanitised = new Map();
  const nameCollisions = [];
  for (const n of flat) {
    if (!n.name) continue;
    const key = sanitiseThreeName(n.name);
    const held = sanitised.get(key);
    if (held && held !== n.name) nameCollisions.push([held, n.name, key]);
    else sanitised.set(key, n.name);
  }

  const isPipelineNode = (name) => name.startsWith(SNAP_PREFIX) || name.startsWith(GRID_PREFIX);
  const mangled = flat
    .filter((n) => !isPipelineNode(n.name) && (THREE_RESERVED.test(n.name) || /\s/.test(n.name)))
    .map((n) => ({ name: n.name, asThreeSeesIt: sanitiseThreeName(n.name) }));

  const duplicateNames = Object.entries(
    flat.reduce((acc, n) => { acc[n.name] = (acc[n.name] || 0) + 1; return acc; }, {}),
  ).filter(([, count]) => count > 1).map(([name, count]) => ({ name, count }));

  // ---- what the pipeline looks for --------------------------------------
  const snapNodes = flat.filter((n) => n.name.startsWith(SNAP_PREFIX));
  const gridNodes = flat.filter((n) => n.name.startsWith(GRID_PREFIX));
  const body = flat.find((n) => n.name === BODY_NODE);

  return {
    file: basename(path),
    readable: true,
    format: container,
    bytes: size,
    generator: json.asset?.generator || null,
    copyright: json.asset?.copyright || null,
    hasBinaryChunk: !!binary,
    extensionsUsed: json.extensionsUsed || [],
    extensionsRequired: json.extensionsRequired || [],
    scene: { name: sceneName, extras },
    counts: {
      nodes: flat.length,
      meshNodes: meshNodes.length,
      meshes: (json.meshes || []).length,
      materials: (json.materials || []).length,
      images: (json.images || []).length,
      animations: (json.animations || []).length,
      skins: (json.skins || []).length,
      cameras: (json.cameras || []).length,
      triangles,
      vertices,
    },
    extentFileUnits: extent,
    boundsFileUnits: hasExtent ? { min: lo, max: hi } : null,
    unitGuesses: extent ? unitCandidates(extent) : [],
    textures,
    mangled,
    nameCollisions: nameCollisions.map(([a, b, key]) => ({ a, b, collapsesTo: key })),
    duplicateNames,
    scaledNodes: flat
      .filter((n) => n.worldScale.some((s) => Math.abs(s - 1) > 1e-6))
      .map((n) => ({ name: n.name, worldScale: n.worldScale.map((s) => Math.round(s * 1e6) / 1e6) })),
    nonTriangleMeshes: meshNodes
      .filter((n) => n.mesh.modes.some((m) => !(m in TRIANGLES_FOR_MODE)))
      .map((n) => ({ name: n.name, modes: n.mesh.modes })),
    missingAccessorBounds: meshNodes.filter((n) => n.mesh.missingBounds).map((n) => n.name),
    confgr: {
      declared: extras?.confgr || null,
      grids: extras?.confgrGrids || null,
      spans: extras?.confgrSpans || null,
      roles: extras?.confgrRoles || null,
      conditions: extras?.confgrConditions || null,
      rolls: extras?.confgrRolls || null,
      options: extras?.confgrOptions || null,
      bodyNode: body ? { min: body.min, max: body.max } : null,
      snapNodes: snapNodes.map((n) => n.name),
      gridNodes: gridNodes.map((n) => n.name),
      collisionNodes: flat.filter((n) => n.name.startsWith(COLLISION_PREFIX)).map((n) => n.name),
      dimensionNode: flat.some((n) => n.name === DIMENSION_NODE),
    },
    nodes: flat.map((n) => ({
      name: n.name,
      path: n.path,
      triangles: n.mesh?.triangles ?? null,
      min: n.min,
      max: n.max,
    })),
  };
}

// ---------------------------------------------------------------- audit
//
// Two lists, and the distinction matters.
//
// BLOCKERS are what extractComponent actually throws on, with the same codes,
// so this output maps one-to-one onto the pipeline. The loader stops at the
// first one; a real file has several, so they are all reported and ordered by
// what has to be fixed first — no point centring the origin on a model whose
// units are wrong.
//
// WARNINGS load fine and bite later. Most of them have bitten already.

const CODES = {
  UNREADABLE: 'The pipeline cannot read this format.',
  NO_DECLARED_SIZE: 'No real-world size declared in scene extras.',
  NO_BODY: `No node named "${BODY_NODE}".`,
  SCALE_MISMATCH: 'Declared size does not match the geometry.',
  ORIGIN_NOT_AT_BASE: 'Origin is not at the base.',
  ORIGIN_NOT_CENTRED: 'Origin is not centred in plan.',
  NO_SNAPS: 'No snap planes and no attach grids.',
  NAME_COLLISION: 'Two node names are indistinguishable to three.js.',
  SNAP_NAME_MALFORMED: 'A snap node name does not parse.',
  SNAP_NAME_DUPLICATE: 'Two nodes share a name.',
  SNAP_ROLE_INVALID: 'A declared role is not "socket" or "plug".',
  GRID_NOT_DECLARED: 'A grid plane has no declaration in extras.',
};

export function audit(report) {
  const blockers = [];
  const warnings = [];
  const add = (list, code, detail, fix) => list.push({ code, says: CODES[code] || code, detail, fix });

  if (!report.readable) {
    add(blockers, 'UNREADABLE', report.format, report.advice);
    return { blockers, warnings, verdict: 'not a runtime format' };
  }

  const c = report.confgr;

  // ---- Rule 1: units and declared size ----------------------------------
  if (!c.declared || c.declared.widthMm == null) {
    const metres = report.unitGuesses.find((g) => g.unit === 'metres');
    add(blockers, 'NO_DECLARED_SIZE',
      report.extentFileUnits
        ? `Geometry spans ${report.extentFileUnits.map((v) => v.toFixed(3)).join(' x ')} in file units`
        : 'no geometry to measure',
      'Add confgr { widthMm, heightMm, depthMm } to the scene extras on export. '
      + (metres?.plausible
        ? `Read as metres this is ${metres.dimsMm.join(' x ')}mm, which looks like real furniture — `
          + 'so the file is probably already in glTF\'s native metres.'
        : 'Check the unit guesses below first: none of the readings look like furniture, '
          + 'so the export scale is likely wrong.'));
  }

  if (!c.bodyNode) {
    add(blockers, 'NO_BODY',
      `nodes present: ${report.counts.nodes}`,
      `Rename the visible geometry to "${BODY_NODE}" (or merge it into one node with that name). `
      + 'The pipeline refuses to guess which node is the product.');
  }

  if (c.declared && c.bodyNode) {
    const measured = {
      widthMm: mm(c.bodyNode.max[0] - c.bodyNode.min[0]),
      heightMm: mm(c.bodyNode.max[1] - c.bodyNode.min[1]),
      depthMm: mm(c.bodyNode.max[2] - c.bodyNode.min[2]),
    };
    const drift = Math.max(
      Math.abs(measured.widthMm - c.declared.widthMm),
      Math.abs(measured.heightMm - c.declared.heightMm),
      Math.abs(measured.depthMm - c.declared.depthMm),
    );
    if (drift > SCALE_TOLERANCE_MM) {
      // Name the ratio rather than describing how to spot it. A consistent
      // factor across all three axes IS the diagnosis: 1000 is a
      // metres/millimetres mix-up, 25.4 is inches, 10 is centimetres. A ratio
      // that differs per axis is a non-uniform scale, which is a different and
      // worse problem — usually a stretched node rather than a unit error.
      const ratios = [
        measured.widthMm / c.declared.widthMm,
        measured.heightMm / c.declared.heightMm,
        measured.depthMm / c.declared.depthMm,
      ].map((r) => (Number.isFinite(r) ? r : NULL_RATIO));

      const uniform = ratios.every((r) => Math.abs(r - ratios[0]) / ratios[0] < 0.01);
      const known = { 1000: 'metres declared as millimetres', 100: 'metres declared as centimetres',
        25.4: 'inches', 10: 'centimetres', 304.8: 'feet', 0.001: 'millimetres declared as metres',
        0.0393701: 'millimetres declared as inches' };
      const near = uniform
        ? Object.entries(known).find(([factor]) => Math.abs(ratios[0] / Number(factor) - 1) < 0.02)
        : null;

      add(blockers, 'SCALE_MISMATCH',
        `declared ${c.declared.widthMm}x${c.declared.heightMm}x${c.declared.depthMm}mm, `
        + `measured ${measured.widthMm}x${measured.heightMm}x${measured.depthMm}mm `
        + `(out by ${drift.toFixed(1)}mm)`,
        `The geometry is ${uniform ? `${ratios[0].toFixed(4).replace(/\.?0+$/, '')}x` : 'unevenly'} `
        + `${uniform ? 'the declared size' : `scaled (${ratios.map((r) => r.toFixed(3)).join(', ')})`}. `
        + (near
          ? `That factor is ${near[1]} — fix the declaration if the model is right, or rescale `
            + 'the model if the declaration came from the supplier\'s datasheet.'
          : uniform
            ? 'That is not a standard unit conversion, so it is more likely an arbitrary scale '
              + 'applied somewhere in the export. Check for a scale on the node or the scene root.'
            : 'A DIFFERENT factor per axis is a stretched model, not a unit error. Find the '
              + 'non-uniform scale and apply or remove it in the modeller.'));
    }

    // ---- Rule 2: origin at base centre ---------------------------------
    if (Math.abs(c.bodyNode.min[1]) > 1e-4) {
      add(blockers, 'ORIGIN_NOT_AT_BASE',
        `base sits at y=${c.bodyNode.min[1].toFixed(4)}`,
        'Move the geometry so its lowest point is y=0. AR drops a model onto a floor plane; '
        + 'an origin at the mesh centre buries half the product in the carpet.');
    }
    const centreX = (c.bodyNode.max[0] + c.bodyNode.min[0]) / 2;
    const centreZ = (c.bodyNode.max[2] + c.bodyNode.min[2]) / 2;
    if (Math.abs(centreX) > 1e-4 || Math.abs(centreZ) > 1e-4) {
      add(blockers, 'ORIGIN_NOT_CENTRED',
        `plan centre is (${centreX.toFixed(4)}, ${centreZ.toFixed(4)})`,
        'Centre the geometry on the origin in X and Z. Off-centre, rotation swings the part '
        + 'off its own snap points.');
    }
  }

  // ---- Snaps ------------------------------------------------------------
  //
  // A part may declare that it fixes to the wall and joins nothing, and then no
  // snaps is the correct answer rather than a missing authoring step. The YouK
  // shoe rack is the case: its sheet is a spirit level, a drill and wall plugs,
  // with no ladder in it anywhere. Everything else still fails loudly.
  const wallMounted = c.declared?.mounting === 'wall';

  if (!c.snapNodes.length && !c.gridNodes.length && !wallMounted) {
    add(blockers, 'NO_SNAPS',
      'none found',
      `Add flat 4-vertex planes named ${SNAP_PREFIX}<mask>.<label>, local +Z facing outward, `
      + 'at each place the part joins another. This is the authoring step no converter does '
      + 'for you — see tools/AUTHORING.md.');
  }

  if (wallMounted && (c.snapNodes.length || c.gridNodes.length)) {
    add(warnings, 'MOUNTING_WALL_WITH_SNAPS',
      `declared mounting "wall" but carries ${c.snapNodes.length + c.gridNodes.length} attach point(s)`,
      'A wall-fixed part joins nothing. Either drop the declaration or drop the snaps — '
      + 'as it stands the app will offer it both ways.');
  }

  for (const name of c.snapNodes) {
    const rest = name.slice(SNAP_PREFIX.length);
    const parts = rest.split('.');
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      add(blockers, 'SNAP_NAME_MALFORMED', name,
        `Expected exactly ${SNAP_PREFIX}<mask>.<label> — one mask, one label, two dots in total.`);
    }
  }

  for (const [name, role] of Object.entries(c.roles || {})) {
    if (role !== 'socket' && role !== 'plug') {
      add(blockers, 'SNAP_ROLE_INVALID', `${name} = "${role}"`,
        'A role is "socket" (offers a place) or "plug" (takes one), or absent for either.');
    }
  }

  for (const name of c.gridNodes) {
    if (!c.grids || !c.grids[name]) {
      add(blockers, 'GRID_NOT_DECLARED', name,
        `Add confgrGrids["${name}"] = { cols, rows, pitchXMm, pitchYMm } to the scene extras. `
        + 'The plane\'s drawn size must equal cols x pitch or the markers will not sit on the webbing.');
    }
  }

  for (const dup of report.duplicateNames) {
    add(blockers, 'SNAP_NAME_DUPLICATE', `"${dup.name}" appears ${dup.count} times`,
      'Node names are identifiers here. Make them unique before export.');
  }

  for (const col of report.nameCollisions || []) {
    add(blockers, 'NAME_COLLISION',
      `"${col.a}" and "${col.b}" both collapse to "${col.collapsesTo}"`,
      'Rename one. three.js strips . : / [ ] from node names, so these two are the same '
      + 'object to it, and a snap would attach to the wrong face. The loader refuses the file.');
  }

  // ---- Warnings ---------------------------------------------------------
  if (report.mangled.length) {
    warnings.push({
      code: 'THREE_NAME_MANGLING',
      says: `${report.mangled.length} non-pipeline node name(s) contain characters three.js strips.`,
      detail: report.mangled.slice(0, 6).map((m) => `${m.name} -> ${m.asThreeSeesIt}`),
      fix: 'No collisions, so nothing breaks. Snap and grid names are exempt — the loader reads '
        + 'those from the raw glTF JSON so their dots survive. Worth knowing if you match any '
        + 'other node name by string.',
    });
  }

  if (report.scaledNodes.length) {
    warnings.push({
      code: 'BAKED_SCALE',
      says: `${report.scaledNodes.length} node(s) carry a scale factor.`,
      detail: report.scaledNodes.slice(0, 6),
      fix: 'Apply the scale in the modeller and re-export. A node-level scale is the usual '
        + 'reason a model measures right on screen and wrong in the pipeline, and it also '
        + 'skews snap plane sizes.',
    });
  }

  if (report.counts.animations || report.counts.skins) {
    warnings.push({
      code: 'NOT_STATIC',
      says: `Contains ${report.counts.animations} animation(s) and ${report.counts.skins} skin(s).`,
      detail: null,
      fix: 'A component is a static mesh. Animation and skinning survive glTF but not the '
        + 'USDZ conversion AR needs, so strip them.',
    });
  }

  if (report.nonTriangleMeshes.length) {
    warnings.push({
      code: 'NON_TRIANGLE_PRIMITIVES',
      says: 'Some meshes use point, line or strip primitives.',
      detail: report.nonTriangleMeshes,
      fix: 'Triangulate on export. Strips and fans render but many pipelines, including '
        + 'USDZ conversion, handle them badly.',
    });
  }

  if (report.missingAccessorBounds.length) {
    warnings.push({
      code: 'NO_ACCESSOR_BOUNDS',
      says: 'Some POSITION accessors have no min/max, which the spec requires.',
      detail: report.missingAccessorBounds.slice(0, 6),
      fix: 'Re-export with a compliant exporter. Sizes reported here may be incomplete, and '
        + 'viewers use these for frustum culling — parts vanish at some camera angles without them.',
    });
  }

  const external = report.textures.filter((t) => t.uri);
  if (external.length) {
    warnings.push({
      code: 'EXTERNAL_TEXTURES',
      says: `${external.length} texture(s) live in separate files.`,
      detail: external.map((t) => t.uri),
      fix: 'Export as .glb, or the model will not travel. A .gltf with sibling .bin and image '
        + 'files loads only where all of them were copied.',
    });
  }

  const unhandled = (report.extensionsRequired || []).filter(
    (e) => !['KHR_materials_variants', 'KHR_texture_basisu', 'KHR_draco_mesh_compression',
      'EXT_meshopt_compression', 'KHR_materials_unlit', 'KHR_mesh_quantization'].includes(e),
  );
  if (unhandled.length) {
    warnings.push({
      code: 'UNHANDLED_REQUIRED_EXTENSION',
      says: 'The file REQUIRES extensions the viewer may not implement.',
      detail: unhandled,
      fix: 'A required extension a loader lacks makes the whole file unloadable. Re-export '
        + 'without it, or confirm three.js supports it.',
    });
  }

  if (report.counts.triangles > 150000) {
    warnings.push({
      code: 'TRIANGLE_BUDGET',
      says: `${report.counts.triangles.toLocaleString()} triangles in one component.`,
      detail: null,
      fix: 'Fine for one hero part, too heavy for twenty in a configuration. Decimate, or plan '
        + 'on Draco/meshopt. A phone running AR is the real constraint, not the desktop.',
    });
  }

  if (report.readable && c.declared && !c.collisionNodes.length) {
    warnings.push({
      code: 'NO_COLLISION_BOX',
      says: 'No collision box.',
      detail: null,
      fix: `Add a box named ${COLLISION_PREFIX}<part> matching the part's true extent. Optional `
        + 'today; needed once parts have to refuse to overlap.',
    });
  }

  const verdict = blockers.length === 0
    ? (warnings.length ? 'loads as a component, with warnings' : 'loads as a component')
    : `${blockers.length} blocker${blockers.length === 1 ? '' : 's'} before this can load`;

  return { blockers, warnings, verdict };
}

// ---------------------------------------------------------------- rendering

const bytesHuman = (n) => (n >= 1048576 ? `${(n / 1048576).toFixed(1)} MB`
  : n >= 1024 ? `${(n / 1024).toFixed(0)} KB` : `${n} bytes`);

function render(report, result) {
  const out = [];
  const line = (s = '') => out.push(s);
  const heading = (s) => { line(); line(s); line('-'.repeat(s.length)); };

  line(`${report.file}  ${bytesHuman(report.bytes)}  ${report.format}`);
  if (!report.readable) {
    line();
    line(`  Format:  ${report.format}`);
    line(`  ${report.advice}`);
    return out.join('\n');
  }

  if (report.generator) line(`generated by: ${report.generator}`);
  if (report.copyright) line(`copyright: ${report.copyright}`);

  heading('Contents');
  const k = report.counts;
  line(`  ${k.nodes} nodes (${k.meshNodes} with geometry), ${k.meshes} meshes, `
    + `${k.materials} materials, ${k.images} images`);
  line(`  ${k.triangles.toLocaleString()} triangles, ${k.vertices.toLocaleString()} vertices`);
  if (k.animations || k.skins || k.cameras) {
    line(`  ${k.animations} animations, ${k.skins} skins, ${k.cameras} cameras`);
  }
  if (report.extensionsUsed.length) line(`  extensions used: ${report.extensionsUsed.join(', ')}`);
  if (report.extensionsRequired.length) line(`  extensions REQUIRED: ${report.extensionsRequired.join(', ')}`);

  heading('Size');
  if (!report.extentFileUnits) {
    line('  No measurable geometry.');
  } else {
    line(`  Spans ${report.extentFileUnits.map((v) => v.toFixed(4)).join(' x ')} in the file's own units.`);
    line();
    line('  Read as        would be (mm)              plausible?');
    for (const g of report.unitGuesses) {
      const mark = g.likeliest ? 'yes  <- likeliest' : g.plausible ? 'yes' : 'no';
      line(`  ${g.unit.padEnd(14)} ${g.dimsMm.join(' x ').padEnd(26)} ${mark}`);
    }
    line();
    line('  glTF\'s native unit is METRES, and this pipeline authors in metres with the real');
    line('  size declared separately in millimetres. More than one reading can look plausible,');
    line('  so "likeliest" only means closest to typical furniture proportions - confirm against');
    line('  the supplier\'s published dimensions before trusting it.');
  }

  heading('What the pipeline found');
  const c = report.confgr;
  line(`  declared size:   ${c.declared ? `${c.declared.widthMm} x ${c.declared.heightMm} x ${c.declared.depthMm} mm` : 'ABSENT'}`);
  line(`  "${BODY_NODE}" node:     ${c.bodyNode ? 'present' : 'ABSENT'}`);
  line(`  snap planes:     ${c.snapNodes.length ? c.snapNodes.length : 'none'}`);
  for (const n of c.snapNodes) {
    const role = c.roles?.[n] ? ` [${c.roles[n]}]` : '';
    const span = c.spans?.[n] ? ` span ${c.spans[n].cols}x${c.spans[n].rows}` : '';
    // A roll is a turn about the joint's own axis. Invisible in a screenshot and
    // invisible in the status line, and it tilts a whole desk.
    const roll = c.rolls?.[n] ? ` roll ${c.rolls[n] > 0 ? '+' : ''}${c.rolls[n]} deg` : '';
    line(`                     ${n}${role}${span}${roll}`);
    // A condition is invisible in a screenshot and invisible in the status
    // line, and it makes a part refuse to fit. Show it wherever the model is
    // being explained, or the first symptom is "why won't this go anywhere".
    const cond = c.conditions?.[n];
    if (cond) {
      const clauses = Object.entries(cond).filter(([k]) => k !== 'because');
      for (const [clause, value] of clauses) {
        const shown = Array.isArray(value)
          ? `${value.length} allowed: ${value.slice(0, 4).join(', ')}${value.length > 4 ? ', …' : ''}`
          : JSON.stringify(value);
        line(`                       only where ${clause} — ${shown}`);
      }
      if (cond.because) line(`                       "${cond.because}"`);
    }
  }
  line(`  attach grids:    ${c.gridNodes.length ? c.gridNodes.length : 'none'}`);
  for (const n of c.gridNodes) {
    const g = c.grids?.[n];
    line(`                     ${n}${g ? ` ${g.cols}x${g.rows} @ ${g.pitchXMm}x${g.pitchYMm}mm` : ' (NOT DECLARED)'}`);
  }
  line(`  collision box:   ${c.collisionNodes.length ? c.collisionNodes.join(', ') : 'none'}`);
  line(`  dimension box:   ${c.dimensionNode ? 'present' : 'none'}`);
  line(`  options:         ${c.options ? Object.keys(c.options).join(', ') : 'none'}`);

  if (report.nodes.length) {
    heading(`Nodes (${report.nodes.length})`);
    const shown = report.nodes.slice(0, 40);
    for (const n of shown) {
      const tris = n.triangles != null ? `${n.triangles.toLocaleString()} tris` : '';
      line(`  ${n.name.padEnd(38).slice(0, 38)} ${tris}`);
    }
    if (report.nodes.length > shown.length) {
      line(`  ... and ${report.nodes.length - shown.length} more (use --json for all)`);
    }
  }

  if (result.blockers.length) {
    heading(`Blockers (${result.blockers.length}) — fix in this order`);
    result.blockers.forEach((b, i) => {
      line(`  ${i + 1}. [${b.code}] ${b.says}`);
      if (b.detail) line(`     found: ${typeof b.detail === 'string' ? b.detail : JSON.stringify(b.detail)}`);
      line(`     fix:   ${b.fix}`);
      line();
    });
  }

  if (result.warnings.length) {
    heading(`Warnings (${result.warnings.length}) — loads, but worth knowing`);
    result.warnings.forEach((w) => {
      line(`  [${w.code}] ${w.says}`);
      if (w.detail) {
        const d = Array.isArray(w.detail) ? w.detail : [w.detail];
        for (const item of d) line(`     ${typeof item === 'string' ? item : JSON.stringify(item)}`);
      }
      line(`     ${w.fix}`);
      line();
    });
  }

  heading('Verdict');
  line(`  ${result.verdict}`);
  return out.join('\n');
}

// ---------------------------------------------------------------- cli

function expand(target) {
  const stat = statSync(target);
  if (!stat.isDirectory()) return [target];
  return readdirSync(target)
    // <id>.converted.glb is a converter output that add-snaps.py consumes. It
    // is an input, not a candidate component, and reporting it as blocked would
    // bury the parts that genuinely need attention. Name one explicitly to
    // inspect it anyway.
    .filter((f) => !f.toLowerCase().endsWith('.converted.glb'))
    .filter((f) => READABLE.has(extname(f).toLowerCase()) || extname(f).toLowerCase() in KNOWN_UNREADABLE)
    .sort()
    .map((f) => join(target, f));
}

function main(argv) {
  const asJson = argv.includes('--json');
  const targets = argv.filter((a) => !a.startsWith('--'));

  if (!targets.length) {
    process.stdout.write(
      'Usage: node tools/inspect-model.mjs <file.glb|file.gltf|directory> [...] [--json]\n\n'
      + 'Reports what a model is and what stands between it and being a confgr component.\n'
      + 'Reads nothing but metadata, decodes no vertex data, and modifies nothing.\n',
    );
    return 0;
  }

  const files = targets.flatMap(expand);
  if (!files.length) {
    process.stdout.write('No .glb or .gltf files found there.\n');
    return 1;
  }

  const results = [];
  let worstExit = 0;

  for (const file of files) {
    let report;
    let result;
    try {
      report = inspect(file);
      result = audit(report);
    } catch (err) {
      report = { file: basename(file), readable: false, format: 'unparseable', bytes: 0, advice: err.message };
      result = { blockers: [{ code: 'UNPARSEABLE', says: err.message, detail: null, fix: 'Check the file is not truncated or renamed.' }], warnings: [], verdict: 'could not be read' };
    }

    if (result.blockers.length) worstExit = 1;
    results.push({ ...report, audit: result });

    if (!asJson) {
      process.stdout.write(`${'='.repeat(74)}\n`);
      process.stdout.write(`${render(report, result)}\n`);
    }
  }

  if (asJson) process.stdout.write(`${JSON.stringify(results, null, 2)}\n`);
  else if (files.length > 1) {
    process.stdout.write(`\n${'='.repeat(74)}\nSummary\n`);
    for (const r of results) {
      process.stdout.write(`  ${r.file.padEnd(34)} ${r.audit.verdict}\n`);
    }
  }

  return worstExit;
}

// Only run when invoked directly, so the module stays importable from tests.
const invokedDirectly = process.argv[1] && process.argv[1].endsWith('inspect-model.mjs');
if (invokedDirectly) process.exitCode = main(process.argv.slice(2));
